export const metadata = { title: "Terms of Use | TravelWithUs" };

const sections = [
  {
    title: "1. Acceptance of Terms",
    body: "By accessing or using TravelWithUs you agree to be bound by these Terms of Use and our Privacy Policy. If you do not agree, please discontinue use immediately.",
  },
  {
    title: "2. Eligibility",
    body: "You must be at least 18 years of age to create an account and make bookings. By using the platform you represent that you meet this requirement.",
  },
  {
    title: "3. Bookings & Payments",
    body: "All bookings are subject to availability and confirmation. Prices displayed are per person in USD. Payment is processed securely through Stripe. A booking is confirmed only upon receipt of full payment and a confirmation email.",
  },
  {
    title: "4. Cancellations & Refunds",
    body: "Free cancellation is available up to 14 days before the travel start date. Cancellations within 14 days incur a 10% fee. No-shows are non-refundable. Refunds are processed within 5–10 business days to the original payment method.",
  },
  {
    title: "5. AI-Generated Itineraries",
    body: "Itineraries are generated by AI and are provided as a planning guide. TravelWithUs does not guarantee the accuracy, completeness, or fitness of AI-generated content for any specific purpose. Users are responsible for verifying opening hours, entry requirements, and local conditions.",
  },
  {
    title: "6. User Conduct",
    body: "You agree not to misuse the platform for unlawful purposes, submit false information, attempt to gain unauthorised access, or disrupt service availability. We reserve the right to suspend or terminate accounts that violate these terms.",
  },
  {
    title: "7. Intellectual Property",
    body: "All content on TravelWithUs including text, design, logos, and AI outputs is the property of TravelWithUs or its licensors. You may not reproduce or distribute content without written permission.",
  },
  {
    title: "8. Limitation of Liability",
    body: "TravelWithUs is not liable for indirect, incidental, or consequential damages arising from use of the platform, travel disruptions, or third-party service failures. Our total liability shall not exceed the amount paid for the relevant booking.",
  },
  {
    title: "9. Governing Law",
    body: "These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts of Mumbai, India.",
  },
  {
    title: "10. Changes to Terms",
    body: "We reserve the right to update these Terms at any time. Continued use of the platform after changes constitutes acceptance. Material changes will be communicated with at least 14 days' notice.",
  },
];

export default function TermsPage() {
  return (
    <main className="min-h-screen py-20 px-6" style={{ background: "var(--bg)" }}>
      <div className="mx-auto max-w-3xl">
        <p className="text-sm font-semibold uppercase tracking-widest mb-3" style={{ color: "var(--primary)" }}>Legal</p>
        <h1 className="text-4xl font-extrabold mb-2" style={{ color: "var(--heading)" }}>Terms of Use</h1>
        <p className="text-sm mb-12" style={{ color: "var(--muted)" }}>Last updated: 1 March 2026</p>

        <div className="space-y-10">
          {sections.map((s) => (
            <div key={s.title}>
              <h2 className="text-lg font-bold mb-3" style={{ color: "var(--heading)" }}>{s.title}</h2>
              <p className="text-sm leading-relaxed" style={{ color: "var(--body)" }}>{s.body}</p>
            </div>
          ))}
        </div>

        <div
          className="mt-14 rounded-2xl p-6 text-sm"
          style={{ background: "var(--surface)", border: "1px solid var(--border)", color: "var(--body)" }}
        >
          Questions? Email{" "}
          <a href="mailto:legal@travelwithus.app" className="underline" style={{ color: "var(--primary)" }}>
            legal@travelwithus.app
          </a>
        </div>
      </div>
    </main>
  );
}
